### Test with expired token
GET https://localhost:7113/api/User/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MTEzIiwiZXhwIjoxNzU1NzExOTE2LCJzdWIiOiJ0ZXN0LXVzZXIxIiwiZW1haWwiOiJ0ZXN0dXNlcjFAdGVzdC5jb20iLCJqdGkiOiJjYjEyNjE1MC0yZmYwLTRjMDgtYjc5My03NmYxNzM0ZTJkMDIiLCJVc2VyR3VpZCI6IjYyMmI2YzgwLWI3NzktNDYyOS1iNzFjLWJkNmEyMzU2MjMwNyIsImlhdCI6MTc1NTcxMTczNiwibmJmIjoxNzU1NzExNzM2fQ.cZYmQdNqmYW0dzrRiCkuoGsmff0VD0_hoqFCpnu2-Jg
Content-Type: application/json
