CREATE TABLE Users (
    UserId INT PRIMARY KEY IDENTITY(1,1),
    UserName NVARCHAR(50) UNIQUE NOT NULL,
    Email NVARCHAR(100) UNIQUE NOT NULL,
    PasswordHash NVARCHAR(MAX) NOT NULL,
    RefreshToken NVARCHAR(MAX),
    RefreshTokenExpiration DATETIME,
    CreatedAt DATETIME DEFAULT GETDATE()
);
