CREATE TABLE Users (
    UserId INT PRIMARY KEY IDENTITY(1,1),
    UserGuid UNIQUEIDENTIFIER NOT NULL,
    UserName NVARCHAR(50) UNIQUE NOT NULL,
    Email NVARCHAR(100) UNIQUE NOT NULL,
    FirstName NVARCHAR(50),
    LastName NVARCHAR(50),
    PasswordHash NVARCHAR(MAX) NOT NULL,
    RefreshToken NVARCHAR(MAX),
    RefreshTokenExpiration DATETIME,
    CreatedAt DATETIME DEFAULT GETDATE()
);
